export const logsData = [
  { 
    id: 1, 
    channel: 'Email', 
    tur: 'BA', 
    alici: 'finans@bilisim.com', 
    unvan: 'Bilişim Sistemleri A.Ş.', 
    vkn: '1112223334', 
    gonderimZT: '28 Mar 2026 10:00:12', 
    iletimDurumu: 'Ulaştı', 
    okunmaDurumu: 'Okundu', 
    okunmaZT: '28 Mar 2026 10:15:45', 
    hata: null, 
    detay: '250 2.0.0 OK: Message accepted for delivery', 
    history: [
      { ip: '192.168.1.5 (İstanbul)', time: '28 Mar 10:15:45', agent: 'Mozilla/5.0 Chrome/114' }, 
      { ip: '192.168.1.12 (Mobil)', time: '28 Mar 11:00:22', agent: 'iOS Safari' }
    ],
    isKep: false
  },
  { 
    id: 2, 
    channel: 'SMS', 
    tur: 'Cari Bakiye', 
    alici: '+90 555 123 4567', 
    unvan: 'Logosan Yazılım Ltd.', 
    vkn: '5556667778', 
    gonderimZT: '28 Mar 2026 11:30:00', 
    iletimDurumu: 'Hata', 
    okunmaDurumu: 'Okunmadı', 
    okunmaZT: null, 
    hata: 'Operatör Reddi (Numara Kapalı)', 
    detay: 'ERROR 400: Invalid subscriber number. Provider: Turkcell', 
    history: [],
    isKep: false
  },
  { 
    id: 3, 
    channel: 'Email', 
    tur: 'BS', 
    alici: 'muhasebbe@netsistem.com', 
    unvan: 'Netsistem Donanım A.Ş.', 
    vkn: '9998887776', 
    gonderimZT: '29 Mar 2026 09:15:05', 
    iletimDurumu: 'Hata', 
    okunmaDurumu: 'Okunmadı', 
    okunmaZT: null, 
    hata: 'Hard Bounce (Böyle bir adres yok)', 
    detay: '550 5.1.1 User Unknown - Mailbox does not exist', 
    history: [],
    isKep: false
  },
  { 
    id: 4, 
    channel: 'KEP', 
    tur: 'İhtarname', 
    alici: 'zirve@hs03.kep.tr', 
    unvan: 'Zirve Global Hukuk Bürosu', 
    vkn: '1234567890', 
    gonderimZT: '30 Mar 2026 14:00:00', 
    iletimDurumu: 'Ulaştı', 
    okunmaDurumu: 'Okunmadı', 
    okunmaZT: null, 
    hata: null, 
    detay: 'Posta Kutusuna Ulaştı Delili başarıyla oluşturuldu.', 
    history: [], 
    isKep: true 
  },
  { 
    id: 5, 
    channel: 'Email', 
    tur: 'Cari Bakiye', 
    alici: 'info@mikro.com', 
    unvan: 'Mikro Tedarik Ltd.', 
    vkn: '4445556667', 
    gonderimZT: '30 Mar 2026 15:30:11', 
    iletimDurumu: 'Bekliyor', 
    okunmaDurumu: 'Okunmadı', 
    okunmaZT: null, 
    hata: null, 
    detay: 'Message queued for delivery.', 
    history: [],
    isKep: false
  },
  { 
    id: 6, 
    channel: 'Faks', 
    tur: 'Cari Bakiye', 
    alici: '+90 212 555 44 33', 
    unvan: 'Global Teknoloji', 
    vkn: '1112223334', 
    gonderimZT: '29 Mar 2026 10:00:00', 
    iletimDurumu: 'Hata', 
    okunmaDurumu: 'Okunmadı', 
    okunmaZT: null, 
    hata: 'Meşgul / Cevap Yok', 
    detay: 'Line Busy Dial Timeout.', 
    history: [],
    isKep: false
  }
];
